### ISSUE TITLE
java.lang.ClassNotFoundException: com.tcoded.folialib.impl.FoliaImplementation 

### ISSUE THREAD

**Issue by TheDiscordian** [TechnicallyCoded/FoliaLib#13]
```
[19:38:10 WARN]: java.lang.ClassNotFoundException: com.tcoded.folialib.impl.FoliaImplementation                      
[19:38:10 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)           
[19:38:10 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)            
[19:38:10 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)                           
[19:38:10 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[19:38:10 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)                                         
[19:38:10 WARN]:        at PAPIProxyBridge-Bukkit-1.5-da8e891-indev.jar//com.tcoded.folialib.FoliaLib.createServerImpl(FoliaLib.java:112)                                                                                                 
[19:38:10 WARN]:        at PAPIProxyBridge-Bukkit-1.5-da8e891-indev.jar//com.tcoded.folialib.FoliaLib.<init>(FoliaLib.java:34)                                                                                                            
[19:38:10 WARN]:        at PAPIProxyBridge-Bukkit-1.5-da8e891-indev.jar//net.william278.papiproxybridge.BukkitPAPIProxyBridge.onLoad(BukkitPAPIProxyBridge.java:54)                                                                       
[19:38:10 WARN]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[19:38:10 WARN]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[19:38:10 WARN]:        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[19:38:10 WARN]:        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)                                                                                                              
[19:38:10 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:513)             
[19:38:10 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)                
[19:38:10 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1217)                         
[19:38:10 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346)              
[19:38:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)                                           
[19:38:10 ERROR]: [PAPIProxyBridge] Error initializing plugin 'PAPIProxyBridge-Bukkit-1.5-da8e891-indev.jar' in folder 'plugins' (Is it up to date?)
java.lang.IllegalStateException: Failed to create server implementation. Please report this to the FoliaLib GitHub issues page. Forks of server software may not all be supported. If you are using an unofficial fork, please report this to the fork's developers first.                                                                                             at com.tcoded.folialib.FoliaLib.<init>(FoliaLib.java:38) ~[PAPIProxyBridge-Bukkit-1.5-da8e891-indev.jar:?]
        at net.william278.papiproxybridge.BukkitPAPIProxyBridge.onLoad(BukkitPAPIProxyBridge.java:54) ~[PAPIProxyBridge-Bukkit-1.5-da8e891-indev.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:513) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

I cloned Folia, built it. Followed your instructions to import the plugin (so I think), build the plugin, tried to run the server, got this message saying to report the issue.

This is the commit which adds FoliaLib and encounters the error: https://github.com/TheDiscordian/PAPIProxyBridge/commit/06999da4f5bb39c35048596ac5e6cae98aec20aa

**Comment by TechnicallyCoded** [comment]
1. You are using shade optimization (minimize) without telling it to hold onto folialib's classes
2. The lib is not relocated to your own package

**Comment by TheDiscordian** [comment]
> 1. You are using shade optimization (minimize) without telling it to hold onto folialib's classes
> 
>     2. The lib is not relocated to your own package

1. Sorry I'm new to this tooling, and I'm not clear on how else to compile it.

2. I did end up relocating it, my bad. It didn't fix this issue, but I did totally miss that.

**Comment by TheDiscordian** [comment]
This isn't a bug, it's just newbie errors.
