### ISSUE TITLE
1.20.6 not working properly (Paper)

### ISSUE THREAD

**Issue by Skyslycer** [TechnicallyCoded/FoliaLib#17]
Using FoliaLib on 1.20.6, shading and relocating produces this error:

Any ideas on what could cause this or is the support for 1.20.6 and up not there yet? (using version 0.3.1)

```
[12:19:12] [Server thread/INFO]: [HMCWraps] Enabling HMCWraps v1.4.5
[12:19:12] [Server thread/WARN]: java.lang.ClassNotFoundException: de.skyslycer.hmcwraps.shade.folialib.impl.PaperImplementation
[12:19:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[12:19:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[12:19:12] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[12:19:12] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[12:19:12] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:534)
[12:19:12] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:513)
[12:19:12] [Server thread/WARN]: 	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68)
[12:19:12] [Server thread/WARN]: 	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source)
[12:19:12] [Server thread/WARN]: 	at HMCWraps-1.4.5.jar//de.skyslycer.hmcwraps.shade.folialib.FoliaLib.createServerImpl(FoliaLib.java:112)
[12:19:12] [Server thread/WARN]: 	at HMCWraps-1.4.5.jar//de.skyslycer.hmcwraps.shade.folialib.FoliaLib.<init>(FoliaLib.java:34)
[12:19:12] [Server thread/WARN]: 	at HMCWraps-1.4.5.jar//de.skyslycer.hmcwraps.HMCWrapsPlugin.onEnable(HMCWrapsPlugin.java:84)
[12:19:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[12:19:12] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[12:19:12] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[12:19:12] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
[12:19:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604)
[12:19:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553)
[12:19:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675)
[12:19:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[12:19:12] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323)
[12:19:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136)
[12:19:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[12:19:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[12:19:12] [Server thread/ERROR]: Error occurred while enabling HMCWraps v1.4.5 (Is it up to date?)
java.lang.IllegalStateException: Failed to create server implementation. Please report this to the FoliaLib GitHub issues page. Forks of server software may not all be supported. If you are using an unofficial fork, please report this to the fork's developers first.
	at HMCWraps-1.4.5.jar/de.skyslycer.hmcwraps.shade.folialib.FoliaLib.<init>(FoliaLib.java:38) ~[HMCWraps-1.4.5.jar:?]
	at HMCWraps-1.4.5.jar/de.skyslycer.hmcwraps.HMCWrapsPlugin.onEnable(HMCWrapsPlugin.java:84) ~[HMCWraps-1.4.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:19:12] [Server thread/INFO]: [HMCWraps] Disabling HMCWraps v1.4.5
```

**Comment by TechnicallyCoded** [comment]
Do you possibly have the same issue as this person? #13

**Comment by Skyslycer** [comment]
Yes, that fixes it. It might be useful to include this in the README.md.

For anybody searching for a solution:
In your shadowJar task, when you use minimize, you have to exclude the library from minimization.

```kt
tasks {
    shadowJar {
        minimize {
            exclude(dependency("com.tcoded:FoliaLib:.*"))
        }
    }
}
```

**Comment by TechnicallyCoded** [comment]
I'll add this TY
