### ISSUE TITLE
not paper-plugin,yml or plugin.ymñ

### ISSUE THREAD

**Issue by CeoOfYoutube** [TechnicallyCoded/FoliaLib#22]
well, i tried this plugin, and it says this `Caused by: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: plugins\FoliaLib-0.3.4.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:120) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:55) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        ... 21 more
Caused by: java.lang.IllegalArgumentException: plugins\FoliaLib-0.3.4.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.getPluginName(FileProviderSource.java:129) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:101) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:55) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        ... 21 more` help?

**Comment by CeoOfYoutube** [comment]
help how i can delete this, i oppened this by error D:
