### ISSUE TITLE
(first it was a build problem) problem trying to use it with the server

### ISSUE THREAD

**Issue by CeoOfYoutube** [TechnicallyCoded/FoliaLib#23]
sorry but, im a dumbass and i dindn't understand how to install it, im very confused right now jeje (sorry)

**Comment by kaxlabs** [comment]
It's a coding library. You can use it with gradle or maven. The README (front page) has examples.

**Comment by CeoOfYoutube** [comment]
i finally build it, now where is the jar- (i used the build.gradle)

**Comment by CeoOfYoutube** [comment]
nevermind, i got the jar

**Comment by CeoOfYoutube** [comment]
well, i got the jar (finally), i put that in the server and now it says
`[19:56:55 ERROR]: [DirectoryProviderSource] Error preparing plugin context: Directory 'plugins\FoliaLib-0.3.4.jar' failed to update!
java.lang.RuntimeException: Directory 'plugins\FoliaLib-0.3.4.jar' failed to update!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:57) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$prepareContext$1(DirectoryProviderSource.java:33) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:194) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212) ~[?:?]
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.walkFiles(DirectoryProviderSource.java:64) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:31) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:17) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:109) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at net.minecraft.server.Main.main(Main.java:122) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at org.bukkit.craftbukkit.Main.main(Main.java:328) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: plugins\FoliaLib-0.3.4.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:120) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:55) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        ... 21 more
Caused by: java.lang.IllegalArgumentException: plugins\FoliaLib-0.3.4.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.getPluginName(FileProviderSource.java:129) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:101) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:55) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        ... 21 more` sooo

**Comment by TechnicallyCoded** [comment]
It's a library, not a plugin. The jar is already provided to be used as part of your other projects. As Kaxlabs said above, you can use the examples and setup guide from the front page. https://github.com/TechnicallyCoded/FoliaLib

**Comment by CeoOfYoutube** [comment]
fack, im so stupid jaja, sorry, thanks for the help, sorry for wasting our time :(
